### ISSUE TITLE
Artikelüberschriften auf Startseite schließen links nicht bündig ab

### ISSUE THREAD

**Issue by JustThomas** [xwolfde/Piratenkleider#202]
Wenn ein Artikel, der auf der Startseite erscheint, eine Überschrift hat, die über mehr als eine Zeile geht, dann ist die erste Zeile der Überschrift gegenüber den folgenden Zeilen um 4 Pixel nach rechts verschoben. Das sieht m.E. etwas seltsam aus.

![Screenshot von piratenpartei.de](https://cloud.githubusercontent.com/assets/1545787/7234748/85252d80-e789-11e4-8b9a-b1aee7347039.png)

Ich habe ein bisschen im CSS herumgestochert und es liegt wohl an der Zeile
```css
.content-primary a:before{display:inline-block;content:' ';width:0;overflow:hidden;height:18px;margin:0 4px 0 0;background:url('../images/linkicons.gif') no-repeat 0 0}
```
in der Datei `basemod_linkicons.css`.
